[Unit]
After=zerotier-one.service
Wants=zerotier-one.service

[Service]
ExecStartPre=/usr/local/libexec/pti-zeek-render-decoy-capture
ExecReload=
ExecReload=/usr/local/libexec/pti-zeek-render-decoy-capture
ExecReload=/usr/local/zeek/bin/zeekctl deploy
