[Service]
ExecStart=
ExecStart=/usr/bin/tcpdump -Z cowrie -i wlan0 -nn -s 0 -U -C 8 -W 8 -w /var/lib/model2-v7-observer/pcap/transfer.pcap src host 192.168.89.112 and tcp dst port 80 and not (dst net 10.0.0.0/8 or dst net 172.16.0.0/12 or dst net 192.168.0.0/16 or dst net 127.0.0.0/8 or dst net 169.254.0.0/16 or dst net 224.0.0.0/4)
